spring.application.name=localidades
server.port=8081
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
ibge.api.base-url=https://servicodados.ibge.gov.br/api/v1/localidades