spring.application.name=api-gateway
server.port=8080

# CORS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,PATCH,DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

# Rota localidades
spring.cloud.gateway.routes[0].id=localidades
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/localidades/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# Rota noticias
spring.cloud.gateway.routes[1].id=noticias
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/noticias/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=0

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG

# Rota docs localidades
spring.cloud.gateway.routes[2].id=localidades-docs
spring.cloud.gateway.routes[2].uri=http://localhost:8081/
spring.cloud.gateway.routes[2].predicates[0]=Path=/aggregate/localidades/v3/api-docs
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/aggregate/localidades/v3/api-docs, /v3/api-docs

# Rota docs noticias
spring.cloud.gateway.routes[3].id=noticias-docs
spring.cloud.gateway.routes[3].uri=http://localhost:8082/
spring.cloud.gateway.routes[3].predicates[0]=Path=/aggregate/noticias/v3/api-docs
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/aggregate/noticias/v3/api-docs, /v3/api-docs

#===== SWAGGER =====
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.urls[0].name=noticias
springdoc.swagger-ui.urls[0].url=/aggregate/noticias/v3/api-docs

springdoc.swagger-ui.urls[1].name=localidades
springdoc.swagger-ui.urls[1].url=/aggregate/localidades/v3/api-docs
