spring.application.name=api-gateway
server.port=8080

# CORS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

# Rota localidades
spring.cloud.gateway.routes[0].id=localidades
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/localidades/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# Rota noticias
spring.cloud.gateway.routes[1].id=noticias
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/noticias/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=0

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG